In [11]:
import numpy as np
import matplotlib.pyplot as mp

In [31]:
X = np.array([[1,2,3],[3,4,5],[4,5,6]])
print('X : \n',X)

X : 
 [[1 2 3]
 [3 4 5]
 [4 5 6]]


In [22]:
print('Shape:', X.shape)

Shape: (2, 3)


In [32]:
print('Size:', X.size)

Size: 9


In [35]:
print('Dim:',X.ndim)

Dim: 2


In [36]:
print('data type:',X.dtype)

data type: int32


In [37]:
print('Object type:',type(X))

Object type: <class 'numpy.ndarray'>


In [38]:
X.size

9

In [40]:
X.real

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [46]:
Y=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
Y.ndim

3

In [53]:
Y=np.empty(shape=[2,2], dtype=float)
Y

array([[4.24399158e-314, 8.48798317e-314],
       [1.27319747e-313, 1.69759663e-313]])

In [55]:
x0=np.zeros(shape=(3,3), dtype=float, order = 'C')
x0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
x0=np.zeros(shape=(3,3), dtype=float, order = 'F')
x0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
x2=np.arange(10,20)
x2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [61]:
x2=np.arange(10,20)
x2

array([10, 12, 14, 16, 18])

In [100]:
x2=np.arange(50,70)
x2

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69])

In [101]:
x2[0]

50

In [102]:
x2[:5]

array([50, 51, 52, 53, 54])

In [103]:
x2[5:]

array([55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [104]:
x2[5:55:3]

array([55, 58, 61, 64, 67])

In [105]:
x2[5:55:1]

array([55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [76]:
x2.size

20

In [78]:
x2.shape

(20,)

In [111]:
y1=np.array([1,2,3])
y1.ndim

1

In [118]:
y2=np.array([[1],[2],[3]])
print(y2.shape)
print(y2.size)
print(y2.ndim)
print(y2[1])
print(type(y2[1]))

(3, 1)
3
2
[2]
<class 'numpy.ndarray'>


In [106]:
x2

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69])

In [107]:
x2[:3]

array([50, 51, 52])

In [109]:
x2[3:]

array([53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [110]:
x2[5:][:55:2][:3]

array([55, 57, 59])

In [134]:
# original array
a1 = np.array([34,2,33,66,89])
a1

array([34,  2, 33, 66, 89])

In [142]:
## n2 = np.ndarray(5, dtype='object')
n2[:] = a1
n2[2]=89
n2[3]=99
print('Original Array:', a1)
print('Modified Array:', n2)

Original Array: [34 19 33 66 17]
Modified Array: [34 19 89 99 17]


In [143]:
#home work is re-size, re-shape, where, round
x1=np.arange(5)
print('x1:', x1)
print('np.cumsum(x1):',np.cumsum(x1))

x1: [0 1 2 3 4]
np.cumsum(x1): [ 0  1  3  6 10]
