In [2]:
import numpy as np
import matplotlib.pyplot as mp
#1. Create a 1D array of numbers from 0 to 9.
X1 = np.array([0,1,2,3,4,5,6,7,8,9])
print('X1 : \n',X1)
print('dim:', X1.ndim)
x11 = np.arange(0,10)
print(x11)
x12 = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(x12)
print('dim:', x12.ndim)

X1 : 
 [0 1 2 3 4 5 6 7 8 9]
dim: 1
[0 1 2 3 4 5 6 7 8 9]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
dim: 2


In [3]:
#2 Create a 3×3 numpy array of all True’s
X2 = np.ones(shape=(3,3), dtype='bool')
print('x2:',X2)
x21=np.full((3,3), 'True')
print('X21:', x21)
x22=np.empty(shape=(3,3), dtype='bool')
x22.fill(1)
print('x22:', x22)

x2: [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
X21: [['True' 'True' 'True']
 ['True' 'True' 'True']
 ['True' 'True' 'True']]
x22: [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
#3.Given an array as input, print o(nly odd numbers as output
x3 = np.arange(0,10)
print('Array:', x3)
print('Odds in Array:',x3[x3%2==1])

Array: [0 1 2 3 4 5 6 7 8 9]
Odds in Array: [1 3 5 7 9]


In [5]:
#4. Replace all odd numbers in arr with -2
x4 = np.arange(0,10)
print(x4)
x41=[x if not(x%2) else -2 for x in x4]
print(x41)

[0 1 2 3 4 5 6 7 8 9]
[0, -2, 2, -2, 4, -2, 6, -2, 8, -2]


In [6]:
#5.How to reshape an array?
x5 = np.arange(0,10)
print(x5)
x5_rs = x5.reshape(2,5).T
print(x5_rs)

[0 1 2 3 4 5 6 7 8 9]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [7]:
#6. Convert a 1D array to a 2D array with 2 rows
x6 = np.arange(0,10)
print(x6)
print('X6 dim:', x6.ndim)
x6_rs = x6.reshape(5,2).T
print(x6_rs)
print('X6_rs dim:', x6_rs.ndim)

[0 1 2 3 4 5 6 7 8 9]
X6 dim: 1
[[0 2 4 6 8]
 [1 3 5 7 9]]
X6_rs dim: 2


In [8]:
#7. Given an array  a  = [1,2,3,4,5,6,7,8,9] , 
#create  new array b from a such that b includes all odd numbers and 4 multiples.
a = np.arange(1,10)
print(a)
print('odds:',a[a%2==1])
print('xple of 4:', a[a%4==0])
b = a[(a%2==1) | (a%4==0) ]
print(b)

[1 2 3 4 5 6 7 8 9]
odds: [1 3 5 7 9]
xple of 4: [4 8]
[1 3 4 5 7 8 9]


In [9]:
#8.Given array, check if there are any null values and print them out. 
x8=[1,3,4,None,7, 9]
print(x8)
for x in x8: 
    if not x: 
        print(x)
None

[1, 3, 4, None, 7, 9]
None


In [32]:
#9. How to replace all missing values with 0 in a numpy array?
# nan can only be in an array if the array is of type float
from numpy import array, nan
arr = np.array([[5., nan, nan], [nan, 6., nan], [nan, 7., 5.]])
print(arr)
arr = np.nan_to_num(arr, copy=False).astype(np.int) # cast array as int to replace zero
print(arr)

[[ 5. nan nan]
 [nan  6. nan]
 [nan  7.  5.]]
[[5 0 0]
 [0 6 0]
 [0 7 5]]


In [34]:
#10. How to find the count of each unique number in a NumPy array?
x10 = np.array([1,1,1,2,2,2,5,25,1,1])
unique, counts = np.unique(x10, return_counts=True)
print(np.asarray((unique, counts)).T)

[[ 1  5]
 [ 2  3]
 [ 5  1]
 [25  1]]


In [38]:
#11. How to convert a numeric to a categorical (text) array?
import numpy as np
import pandas as pd

a = np.random.rand(2,3) # create a random array
print('a:\n', a)

b = a.flatten() #flatten the arry to one D
print('b:\n', b)

c = pd.cut(b,(0,0.5,1),labels=[0,1]) #bin the arry 
print('c:\n', c)

d = np.reshape(c,(2,3)) # reshape back to 2x3 arry
print('d:\n', d)

e = np.digitize(a, bins=(0.5, 1)) # digitize lets array binning within shape
print('e:\n', e)

a:
 [[0.68679815 0.99847286 0.0652366 ]
 [0.91945196 0.14970983 0.76512527]]
b:
 [0.68679815 0.99847286 0.0652366  0.91945196 0.14970983 0.76512527]
c:
 [1, 1, 0, 1, 0, 1]
Categories (2, int64): [0 < 1]
d:
 [[1 1 0]
 [1 0 1]]
e:
 [[1 1 0]
 [1 0 1]]


In [57]:
# 12. Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. 
# Exclude the elements which are divisible by both
x12 = np.arange(99,299)
#print(x12)
#print('% by 5:',x12[x12%5==0])
#print('% by 7:',x12[x12%7==0])
#print('% by 3:',x12[x12%35!=0])
x12_t = x12[((x12%5==0) | (x12%7==0)) & (x12%35!=0)]
print(x12_t)

[100 110 112 115 119 120 125 126 130 133 135 145 147 150 154 155 160 161
 165 168 170 180 182 185 189 190 195 196 200 203 205 215 217 220 224 225
 230 231 235 238 240 250 252 255 259 260 265 266 270 273 275 285 287 290
 294 295]


In [73]:
#13. Write a program to reverse an array and print (Don’t use inbuilt reverse functions)
x13 = np.arange(12, 38)
print("Original array:")
print(x13)
print("Reverse array:")
x13 = x13[::-1]
print(x13)

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]
